### ISSUE TITLE
type=inline node expansion hint and example

### ISSUE THREAD

**Issue by lolli42** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#186]
People are confused why type=inline has no fieldWizard / fieldInformation like the other elements. In fact, it has, but it needs to be configured on 'ctrl' level (see ctrl container property). This is because inline in the rendering is a container and not an element.

We should at least hint for that in the type=inline docs, including an example. It would be even better if ext:styleguide would have a dedicated table to show-off some different node expansion setups on various type's.

**Comment by steffenk** [comment]
I just started to dig into, and indeed it's very difficult to get an entrance here. Seems i have to do all the html and logic by myself, which is different from the other wizards like add or edit etc.

Maybe it would be quite easier to add a possibility to hook into getLevelInteractionLink, as mostly you need sth like a button for a certain action, in my case to create an export file on the inline childs. Other actions maybe some consistence checks, field updates etc. I would like to do mostly with less code and more API feel like at other places :)

**Comment by linawolf** [comment]
@lolli42 can you give me some hints about how the ctrl can be used to create fieldWizards / fieldInformation  in inline? Then I could maybe create the examples

**Comment by sypets** [comment]
I have created a minimal working example locally. I would like to add it to the documentation next. Feedback is welcome.

A custom fieldWizard is created with the name "demoFieldWizard". It only outputs "hello world" since the output etc. is not the point of this exercise.

## More todos:

* [ ] What this does now is make the wizard active for all "inline" types in t_content. If I would like to add this just to a specific field or deactivate it for a specific field - that is yet to be determined how to do that.

## My example:


1. Create a custom field wizard

```
<?php
declare(strict_types=1);
namespace Sypets\Sypetsexample\Backend\FormEngine;

use TYPO3\CMS\Backend\Form\AbstractNode;

class DemoFieldInformation extends AbstractNode
{
    public function render()
    {
        $result = $this->initializeResultArray();

        $result['html'] = 'hello world!';

        return $result;

    }
}
```

2. Register this node type

ext_localconf.php

```
<?php
// all use statements must come first
use Sypets\Sypetsexample\Backend\FormEngine\DemoFieldInformation;

// Prevent Script from being called directly
defined('TYPO3') or die();

(function () {
    // Add your code here

    $GLOBALS['TYPO3_CONF_VARS']['SYS']['formEngine']['nodeRegistry'][1654355506] = [
        'nodeName' => 'demoFieldWizard',
        'priority' => 30,
        'class' => DemoFieldInformation::class,
    ];

})();

```

3.  Add the wizard to the container for containerRenderType "inline"

Configuration/TCA/Overrrides/tt_content.php

```
$GLOBALS['TCA']['tt_content']['ctrl']['container']['inline']['fieldInformation'] = [
    'demoFieldWizard' => [
        'renderType' => 'demoFieldWizard',
    ],
];
```

4. 

Next, use the inline type somewhere by adding a field in tt_content, e.g. by using code from https://docs.typo3.org/m/typo3/reference-tca/11.5/en-us/ColumnsConfig/Type/Inline/Examples.html#file-abstraction-layer
