### ISSUE TITLE
richtextConfiguration: should we mention the overwrite possibilities with PageTSConfig?

### ISSUE THREAD

**Issue by josefglatz** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#219]
What are you thinking about mentioning the override possibilites with PageTSConfig of the `richtextConfiguration` option in https://docs.typo3.org/typo3cms/TCAReference/ColumnsConfig/Type/Text.html#richtextconfiguration ?

**Comment by sypets** [comment]
@josefglatz Please feel free to submit a PR.

I agree with you and thanks for pointing this out. When I last looked at the page, I missed a description and example that actually used the option richtextConfiguration in Page TSconfig and I found the existing information important but slightly out of scope and think it could better be moved or merged in with rte_ckeditor docs and then (once available) links provided to that from richttextConfiguration. 

Additionally, for the text _"If dealing with the YAML files, be aware it is usually not allowed to base your configuration on existing files and to extend them, but it is required to rely on a full own set of configuration files."_, I think a link should be added, because you read it and think. Ok, but how? But again, I think that text should be moved to the rte_ckeditor docs as well.

**Comment by sypets** [comment]
I corrected my last comment slightly

**Comment by linawolf** [comment]
PageTsConfig is quite outdated, the RTE is configured by YAML now...

**Comment by sypets** [comment]
I think this is not entirely true, RTE is configured with Yaml **and** Page TSconfig (**and** TYPO3_CONF_VARS). See also https://docs.typo3.org/c/typo3/cms-rte-ckeditor/master/en-us/Configuration/ConfigureTypo3.html#page-tsconfig

I am not sure that must be mentioned in the TCA ref. In any case, it is probably better to make a suggestion via PR and keep the issue closed.
