### ISSUE TITLE
dbType 'date' not useable in searchFields

### ISSUE THREAD

**Issue by remonator** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#325]
## Problem
Adding a column of `dbType => date` and `renderType => inputDateTime` into the `searchFields` list yields no results when searching for a record with this date in the List module.

## Question
Am I right to assume that `date` fields are being omitted in [Line 310 of LiveSearch.php](https://github.com/TYPO3/TYPO3.CMS/blob/10.4/typo3/sysext/backend/Classes/Search/LiveSearch/LiveSearch.php#L310)?

## Impact
If so, this should definitely be mentioned in the documentation of the `searchFields` section [here](https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/Ctrl/Index.html#searchfields) and the `search` section of the `inputDateTime` render type [here](https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/inputDateTime.html#search)

**Comment by mbrodala** [comment]
That's true indeed and I assume that it's because the internal DB value (e.g. timestamp) does not necessarily match the value a user would enter (proper date string). Additionally date strings can vary a lot (localized, with/without time, etc.).

Please suggest a change for the page you linked by editing them. :-)
